Use the actual air/water modifiers
CivMC/Finale pull request #22
Opened 2022-07-14 19:55 UTC by nebula161

2022-07-14 20:03 UTC, grepsedawk approved these changes

2022-07-14 20:05 UTC, nebula161 commented
https://github.com/CivMC/Finale/issues/16

2022-07-14 22:37 UTC, Diet-Cola approved these changes

2022-07-14 23:13 UTC, Aleksey-Terzi commented
> Related to #16

Are you sure it fixes any issue from #16?
Did you test it?
Because I don't see how it can do this.
**def.getGroundModifier()** is the default modifier which is used only when config value is not set.
Also, **def.getGroundModifier() == def.getAirModifier() == def.getWaterModifier()**: https://github.com/CivMC/Finale/blob/master/paper/src/main/java/com/github/maxopoly/finale/ConfigParser.java#L374

Yes, this fix is useful though I don't think it fixes KB issues.

2022-07-15 11:01 UTC, grepsedawk commented
Related to entails that it is or could be related to another ticket, not that it's a resolution

2022-07-15 13:53 UTC, Aleksey-Terzi commented
> Related to entails that it is or could be related to another ticket, not that it's a resolution

I mean at the moment this effectively change does nothing because all default modifiers are the same unless I missed something?

2022-07-15 14:16 UTC, Aleksey-Terzi requested changes
I suggest replacing `KnockbackConfig def` to `KnockbackModifier defaultModifier` and pass just one default modifier rather than config:
- https://github.com/CivMC/Finale/blob/master/paper/src/main/java/com/github/maxopoly/finale/ConfigParser.java#L374
- https://github.com/CivMC/Finale/blob/master/paper/src/main/java/com/github/maxopoly/finale/ConfigParser.java#L379

This will help to avoid confusion.

2022-07-15 14:17 UTC, Aleksey-Terzi commented on paper/src/main/java/com/github/maxopoly/finale/ConfigParser.java
>  	private KnockbackConfig parseKnockbackConfig(ConfigurationSection config, String name, KnockbackConfig def) {
This can be changed to:
`private KnockbackConfig parseKnockbackConfig(ConfigurationSection config, String name, KnockbackModifier defaultModifier) {`

2022-08-11 00:38 UTC, Aleksey-Terzi commented on paper/src/main/java/com/github/maxopoly/finale/ConfigParser.java
> +	private KnockbackConfig parseKnockbackConfig(ConfigurationSection config, String name, KnockbackModifier defaultModifier) {
This code won't compile.
`defaultModifier` need to be used inside the method

2023-03-04 05:09 UTC, closed without merging